# Generated by Django 3.0.8 on 2020-08-02 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_auto_20200729_1126'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='trainers',
        ),
        migrations.AlterField(
            model_name='targetresult',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='board.Event'),
        ),
    ]
