# Generated by Django 3.0.8 on 2020-08-03 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0006_auto_20200802_1743'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetresult',
            name='result_ex',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='targetresult',
            name='result_sv',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='targetresult',
            name='target_ex',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='targetresult',
            name='target_sv',
            field=models.FloatField(default=0),
        ),
    ]
