# Generated by Django 3.0.8 on 2020-08-05 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_auto_20200803_1946'),
    ]

    operations = [
        migrations.RenameField(
            model_name='information',
            old_name='user',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='information',
            name='athlete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='information', to='board.Athlete'),
        ),
    ]
