# Generated by Django 3.0.8 on 2020-07-27 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Group of athletes', 'verbose_name_plural': 'Groups of athletes'},
        ),
        migrations.AddField(
            model_name='group',
            name='name',
            field=models.CharField(default='New group', max_length=64),
        ),
    ]
