# Generated by Django 3.0.8 on 2020-07-27 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0002_auto_20200727_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Apparatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_name', models.CharField(max_length=3, null=True, unique=True)),
                ('name', models.CharField(max_length=30, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Apparatus',
                'verbose_name_plural': 'Apparatus',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=140, null=True)),
                ('date', models.DateTimeField()),
                ('place', models.CharField(max_length=120, null=True)),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='athletes.Group'),
        ),
        migrations.AlterField(
            model_name='athlete',
            name='birth_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(default='New group', max_length=120),
        ),
    ]
