# Generated by Django 3.0.8 on 2020-07-27 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0006_auto_20200727_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apparatus',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='apparatus',
            name='short_name',
            field=models.CharField(max_length=3, unique=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
        migrations.CreateModel(
            name='TargetResults',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletes.Apparatus')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletes.Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletes.Event')),
            ],
            options={
                'verbose_name': 'TargetResults',
                'verbose_name_plural': 'TargetResults',
            },
        ),
    ]
