# Generated by Django 3.0.8 on 2020-07-27 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('athletes', '0007_auto_20200727_1536'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_sv', models.FloatField(blank=True, null=True)),
                ('target_ex', models.FloatField(blank=True, null=True)),
                ('result_sv', models.FloatField(blank=True, null=True)),
                ('result_ex', models.FloatField(blank=True, null=True)),
                ('apparatus', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletes.Apparatus')),
                ('athlete', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletes.Athlete')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='athletes.Event')),
            ],
            options={
                'verbose_name': 'TargetResult',
                'verbose_name_plural': 'TargetsResults',
            },
        ),
        migrations.DeleteModel(
            name='TargetResults',
        ),
    ]
